name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Purescript and Spago
        run: |
          npm i -g purescript
          npm i -g spago@next

      - name: Build
        run: spago build --strict

      - name: Test
        run: spago test --strict
